-- Run this query in your Supabase SQL Editor

CREATE TABLE admissions (
  id bigint generated by default as identity primary key,
  "studentName" text not null,
  "parentsName" text not null,
  "studentNumber" text not null,
  "birthCertificate" text not null,
  "address" text not null,
  "targetClass" text not null,
  status text not null default 'Pending',
  date timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE admissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON admissions FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON admissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON admissions FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON admissions FOR DELETE USING (true);
