-- 📝 SUPER-INTEGRATED SETUP FOR CHILD CARE HIGH SCHOOL ADMIT CARDS 📝
-- Execute this SQL code in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create Academic Subjects Table (Reference for Exam Routines)
CREATE TABLE IF NOT EXISTS public.academicsubjects (
  id bigint NOT NULL PRIMARY KEY,
  academicyear varchar(255) DEFAULT '2026',
  classname varchar(255) NOT NULL,
  groupname varchar(255) DEFAULT 'N/A',
  subjectname varchar(255) NOT NULL,
  subjectcode varchar(50) DEFAULT NULL,
  subjectnative varchar(255) DEFAULT NULL,
  optional_subject smallint DEFAULT 0,
  combined_subject_id bigint DEFAULT NULL,
  is_combined_parent smallint DEFAULT 0,
  total_mark varchar(5) DEFAULT NULL,
  written_pass_mark varchar(5) DEFAULT NULL,
  mcq_pass_mark varchar(5) DEFAULT NULL,
  practical_pass_mark varchar(5) DEFAULT NULL,
  pass_total_mark varchar(5) DEFAULT '33',
  require_component_pass smallint DEFAULT 0,
  subject_type varchar(50) DEFAULT 'compulsory',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 2. Create Student Admissions Table
CREATE TABLE IF NOT EXISTS public.studentadmissions (
  id bigint NOT NULL PRIMARY KEY,
  studentimage varchar(255) DEFAULT NULL,
  uniqueid varchar(255) DEFAULT NULL,
  session integer DEFAULT 2026,
  class varchar(255) NOT NULL,
  "group" varchar(255) DEFAULT NULL, -- '3' = Science, '2' = Commerce, '1' = Arts
  section varchar(255) DEFAULT NULL,
  shift varchar(255) DEFAULT 'Day',
  residentialstatus varchar(255) DEFAULT NULL,
  stipend varchar(255) DEFAULT NULL,
  admissiondate date DEFAULT NULL,
  nameen varchar(255) NOT NULL,
  namebn varchar(255) DEFAULT NULL,
  dob date DEFAULT NULL,
  brn varchar(255) DEFAULT NULL,
  distbirth varchar(255) DEFAULT NULL,
  religion varchar(255) DEFAULT NULL,
  gender varchar(255) DEFAULT NULL,
  studentnationality varchar(255) DEFAULT 'BANGLADESHI',
  bloodgroup varchar(255) DEFAULT NULL,
  disabilities varchar(255) DEFAULT 'NOT DISABILITIES',
  istribal varchar(255) DEFAULT 'No',
  isorphan varchar(255) DEFAULT 'No',
  presentvillage varchar(255) DEFAULT NULL,
  presentroad varchar(255) DEFAULT NULL,
  presentpo varchar(255) DEFAULT NULL,
  presentpc varchar(255) DEFAULT NULL,
  presentps varchar(255) DEFAULT NULL,
  presentdist varchar(255) DEFAULT NULL,
  permanentvillage varchar(255) DEFAULT NULL,
  permanentroad varchar(255) DEFAULT NULL,
  permanentpo varchar(255) DEFAULT NULL,
  permanentpc varchar(255) DEFAULT NULL,
  permanentps varchar(255) DEFAULT NULL,
  permanentdist varchar(255) DEFAULT NULL,
  fathernameen varchar(255) DEFAULT NULL,
  fathernamebn varchar(255) DEFAULT NULL,
  fathermobile varchar(255) DEFAULT NULL,
  fatheredu varchar(255) DEFAULT NULL,
  fathernid varchar(255) DEFAULT NULL,
  fathernationality varchar(255) DEFAULT NULL,
  fatherprofession varchar(255) DEFAULT NULL,
  fatherincome varchar(255) DEFAULT NULL,
  mothernameen varchar(255) DEFAULT NULL,
  mothernamebn varchar(255) DEFAULT NULL,
  mothermobile varchar(255) DEFAULT NULL,
  motheredu varchar(255) DEFAULT NULL,
  mothernid varchar(255) DEFAULT NULL,
  mothernationality varchar(255) DEFAULT NULL,
  motherprofession varchar(255) DEFAULT NULL,
  motherincome varchar(255) DEFAULT NULL,
  guardianname varchar(255) DEFAULT NULL,
  relation varchar(255) DEFAULT NULL,
  guardianmobile varchar(255) DEFAULT NULL,
  guardiannid varchar(255) DEFAULT NULL,
  guardiannationality varchar(255) DEFAULT NULL,
  guardianprof varchar(255) DEFAULT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 3. Create Student Sub-profiles Table (Maps admissions key `sid` to a `roll` number)
CREATE TABLE IF NOT EXISTS public.studentsubprofiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sid bigint REFERENCES public.studentadmissions(id) ON DELETE CASCADE,
  session integer NOT NULL DEFAULT 2026,
  class varchar(255) NOT NULL,
  "group" varchar(255) DEFAULT NULL,
  section varchar(255) DEFAULT NULL,
  shift varchar(255) DEFAULT 'Day',
  roll varchar(50) NOT NULL,
  active smallint DEFAULT 1,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 4. Create Exam Routines Table
CREATE TABLE IF NOT EXISTS public.examroutines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year varchar(255) NOT NULL DEFAULT '2026',
  class varchar(255) NOT NULL,
  "group" varchar(255) NOT NULL,
  section varchar(50) NOT NULL DEFAULT 'all',
  shift varchar(255) DEFAULT NULL,
  term varchar(255) NOT NULL,
  subject bigint REFERENCES public.academicsubjects(id) ON DELETE CASCADE,
  date date NOT NULL,
  starttime varchar(255) NOT NULL,
  endtime varchar(255) NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 5. Enable Row Level Security (RLS) on all tables for Supabase policy rules
ALTER TABLE public.academicsubjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.studentadmissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.studentsubprofiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.examroutines ENABLE ROW LEVEL SECURITY;

-- 6. Grant Public Access Policies (Insert, Select, Update, Delete)
DROP POLICY IF EXISTS "Enable all access for all users" ON public.academicsubjects;
CREATE POLICY "Enable all access for all users" ON public.academicsubjects FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all access for all users" ON public.studentadmissions;
CREATE POLICY "Enable all access for all users" ON public.studentadmissions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all access for all users" ON public.studentsubprofiles;
CREATE POLICY "Enable all access for all users" ON public.studentsubprofiles FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all access for all users" ON public.examroutines;
CREATE POLICY "Enable all access for all users" ON public.examroutines FOR ALL USING (true) WITH CHECK (true);


-- 🚀 7. Insert Dummy Demo/Seed Records for "Class Nine", Session "2026" and Group "Science (3)"
-- This provides immediate data to load the matrix and preview the elegant admit cards!

-- A. Subjects
INSERT INTO public.academicsubjects (id, classname, groupname, subjectname, subjectcode) VALUES
(101, 'Nine', 'Science', 'Bangla 1st Paper', '101'),
(102, 'Nine', 'Science', 'Bangla 2nd Paper', '102'),
(107, 'Nine', 'Science', 'English 1st Paper', '107'),
(108, 'Nine', 'Science', 'English 2nd Paper', '108'),
(109, 'Nine', 'Science', 'Mathematics', '109'),
(111, 'Nine', 'Science', 'Islam & Moral Education', '111'),
(136, 'Nine', 'Science', 'Physics', '136'),
(137, 'Nine', 'Science', 'Chemistry', '137'),
(138, 'Nine', 'Science', 'Biology', '138')
ON CONFLICT (id) DO NOTHING;

-- B. Student Admissions
INSERT INTO public.studentadmissions (id, uniqueid, session, class, "group", section, nameen, fathernameen, mothernameen, dob, gender, bloodgroup) VALUES
(1001, '202609001', 2026, 'Nine', '3', 'A', 'SAYED ANWAR SHAH', 'SAYED KABIR SHAH', 'MST. LAILY BEGUM', '2011-04-12', 'Male', 'O positive (O+)'),
(1002, '202609002', 2026, 'Nine', '3', 'A', 'NABIHA TASNIM NUR', 'ALHAJ MD. NURUL ISLAM', 'MST. SELINA AKTER', '2011-08-25', 'Female', 'A positive (A+)'),
(1003, '202609003', 2026, 'Nine', '3', 'A', 'TASRIF MAHMOOD JAWAD', 'MD. FAZLUL KARIM', 'NASIMA SULTANA', '2011-12-05', 'Male', 'B positive (B+)')
ON CONFLICT (id) DO NOTHING;

-- C. Student Sub-profiles (Roll Mappings)
INSERT INTO public.studentsubprofiles (id, sid, session, class, "group", section, roll, active) VALUES
(501, 1001, 2026, 'Nine', '3', 'A', '1', 1),
(502, 1002, 2026, 'Nine', '3', 'A', '2', 1),
(503, 1003, 2026, 'Nine', '3', 'A', '3', 1)
ON CONFLICT (id) DO NOTHING;

-- D. Exam Routines
INSERT INTO public.examroutines (id, year, class, "group", section, term, subject, date, starttime, endtime) VALUES
(801, '2026', 'Nine', '3', 'A', '1st Terminal Exam', 101, '2026-06-15', '01:00 PM', '04:00 PM'),
(802, '2026', 'Nine', '3', 'A', '1st Terminal Exam', 102, '2026-06-16', '01:00 PM', '04:00 PM'),
(803, '2026', 'Nine', '3', 'A', '1st Terminal Exam', 107, '2026-06-18', '01:00 PM', '04:00 PM'),
(804, '2026', 'Nine', '3', 'A', '1st Terminal Exam', 108, '2026-06-19', '01:00 PM', '04:00 PM'),
(805, '2026', 'Nine', '3', 'A', '1st Terminal Exam', 136, '2026-06-21', '01:00 PM', '04:00 PM'),
(806, '2026', 'Nine', '3', 'A', '1st Terminal Exam', 137, '2026-06-22', '01:00 PM', '04:00 PM')
ON CONFLICT (id) DO NOTHING;

-- Force refresh the public schema cache so API endpoints detect tables immediately!
NOTIFY pgrst, 'reload schema';
