-- Run these queries in your Supabase SQL Editor to setup ALL tables for the School Admin Panel

-- 1. Notices (Notice Board)
CREATE TABLE IF NOT EXISTS public.notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    details TEXT,
    date TEXT,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Latest Notice (Text Only Ticker)
CREATE TABLE IF NOT EXISTS public.news_tickers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Students
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "studentName" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "studentClass" TEXT NOT NULL,
    roll TEXT,
    phone TEXT,
    name_bn TEXT,
    father_name TEXT,
    mother_name TEXT,
    dob TEXT,
    study_group TEXT,
    section TEXT,
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. School Events (Calendar)
CREATE TABLE IF NOT EXISTS public.school_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Class Diaries
CREATE TABLE IF NOT EXISTS public.diaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    date TEXT NOT NULL,
    class TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. External Results
CREATE TABLE IF NOT EXISTS public.results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "examName" TEXT NOT NULL,
    "resultClass" TEXT NOT NULL,
    "resultType" TEXT,
    "studentId" TEXT,
    link TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 7. Student Marks (Internal Results)
CREATE TABLE IF NOT EXISTS public.student_marks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_number TEXT NOT NULL,
  student_name TEXT,
  class_name TEXT NOT NULL,
  exam_name TEXT NOT NULL,
  subject TEXT NOT NULL,
  marks NUMERIC NOT NULL,
  mcq_marks NUMERIC,
  cq_marks NUMERIC,
  practical_marks NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 8. Processed Results (Internal Results processing cache)
CREATE TABLE IF NOT EXISTS public.processed_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_number TEXT NOT NULL,
  student_name TEXT,
  class_name TEXT NOT NULL,
  exam_name TEXT NOT NULL,
  total_marks NUMERIC,
  gpa NUMERIC,
  grade TEXT,
  rank_roll INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 9. Admissions
CREATE TABLE IF NOT EXISTS public.admissions (
  id bigint generated by default as identity primary key,
  "studentName" text not null,
  "parentsName" text not null,
  "studentNumber" text not null,
  "birthCertificate" text not null,
  "address" text not null,
  "targetClass" text not null,
  status text not null default 'Pending',
  date timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 10. Messages
CREATE TABLE IF NOT EXISTS public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  date timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 11. Gallery Images
CREATE TABLE IF NOT EXISTS public.gallery_images (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text,
  event_date text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Disable Row Level Security (RLS) across all tables for full Admin Panel functionality
-- In a truly production environment, these should be replaced with explicit Admin Policies
ALTER TABLE public.notices DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_tickers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.students DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.diaries DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.results DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_marks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.processed_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.admissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_images DISABLE ROW LEVEL SECURITY;

-- Reload Supabase PostgREST schema cache to ensure UI is updated
NOTIFY pgrst, 'reload schema';
