-- Run these queries in your Supabase SQL Editor

-- 1. Table for admissions
CREATE TABLE IF NOT EXISTS public.admissions (
  id bigint generated by default as identity primary key,
  "studentName" text not null,
  "parentsName" text not null,
  "studentNumber" text not null,
  "birthCertificate" text not null,
  "address" text not null,
  "targetClass" text not null,
  status text not null default 'Pending',
  date timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.admissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for all users" ON public.admissions FOR ALL USING (true) WITH CHECK (true);

-- 2. Table for latest news (Settings)
CREATE TABLE IF NOT EXISTS public.site_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb
);

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for all users" ON public.site_settings FOR ALL USING (true) WITH CHECK (true);

-- 3. Table for Contact Messages
CREATE TABLE IF NOT EXISTS public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  date timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for all users" ON public.messages FOR ALL USING (true) WITH CHECK (true);
