CREATE TABLE IF NOT EXISTS student_marks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_number TEXT NOT NULL,
  student_name TEXT,
  class_name TEXT NOT NULL,
  exam_name TEXT NOT NULL,
  subject TEXT NOT NULL,
  marks NUMERIC NOT NULL,
  mcq_marks NUMERIC,
  cq_marks NUMERIC,
  practical_marks NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE TABLE IF NOT EXISTS processed_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_number TEXT NOT NULL,
  student_name TEXT,
  class_name TEXT NOT NULL,
  exam_name TEXT NOT NULL,
  total_marks NUMERIC,
  gpa NUMERIC,
  grade TEXT,
  rank_roll INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

ALTER TABLE student_marks DISABLE ROW LEVEL SECURITY;
ALTER TABLE processed_results DISABLE ROW LEVEL SECURITY;
