-- Notice Board (Handles Images, PDFs, and Links)
CREATE TABLE IF NOT EXISTS public.notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    details TEXT,
    date TEXT,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Latest Notice (Text Only Ticker)
CREATE TABLE IF NOT EXISTS public.news_tickers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Disable Row Level Security (RLS) for seamless use in Admin Panel, or configure as needed
ALTER TABLE public.notices DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_tickers DISABLE ROW LEVEL SECURITY;

-- If you are enabling file uploads, make sure to insert a public bucket:
-- NOTE: This often cannot be done directly via SQL without superuser privileges on Supabase,
-- but you can create it via your Supabase Dashboard UI -> Storage -> New Bucket -> name it "school_files", make it public.
-- Example SQL (requires specific extensions/functions depending on your environment):
INSERT INTO storage.buckets (id, name, public) 
VALUES ('school_files', 'school_files', true)
ON CONFLICT (id) DO NOTHING;

-- Allows public read access to files
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING ( bucket_id = 'school_files' );

-- Allows public inserts (if RLS is enabled on objects and you want direct uploads to work from your unauthenticated admin panel)
CREATE POLICY "Public Insert" 
ON storage.objects FOR INSERT 
WITH CHECK ( bucket_id = 'school_files' );
