-- First, we drop the old table if it's there (optional, but requested by user to start fresh)
-- DROP TABLE IF EXISTS news_tickers;

CREATE TABLE news_tickers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE news_tickers ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access on news_tickers" 
ON news_tickers FOR SELECT 
USING (true);

-- Allow authenticated users to insert, update, delete
CREATE POLICY "Allow authenticated users to insert on news_tickers" 
ON news_tickers FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to update on news_tickers" 
ON news_tickers FOR UPDATE 
USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to delete on news_tickers" 
ON news_tickers FOR DELETE 
USING (auth.role() = 'authenticated');

-- Insert initial data
INSERT INTO news_tickers (message) VALUES
('Welcome to Child Care High School online portal.'),
('Admission is going on for class 6 to 9 (Session 2024).'),
('Half-yearly examination will commence from 15th July. Please collect admit card.');
