-- Run this query in your Supabase SQL Editor to manage Admin and Teacher access

CREATE TABLE IF NOT EXISTS public.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL CHECK (role IN ('admin', 'teacher')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Turn on Security
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Allow all users to read the roles (needed for login check)
CREATE POLICY "Enable read access for all" ON public.user_roles FOR SELECT USING (true);
CREATE POLICY "Enable all access for all" ON public.user_roles FOR ALL USING (true) WITH CHECK (true);

-- Insert the primary Admin email (replace with your email)
INSERT INTO public.user_roles (email, role) 
VALUES ('yeasindewan77@gmail.com', 'admin')
ON CONFLICT (email) DO NOTHING;
